import type { Lesson } from './types';

const AUDIO = '/audio/standard/gj-08';

/**
 * N3 第 2 课：〜ところだ（将要／正在／刚刚，三态）。JLPT N3。
 * 大纲 notes/LESSON_DRAFT_gj-07-08.md（Luna 2026-09-29「N3 两课你可以先做」；课文按单词等级改过）。
 * 人物：A＝拓也（男，在烤肉店门口打电话）；B＝リン（女，在家做饭）。朋友。
 * 语体：朋友之间普通体；练习第 1 题用丁寧語。
 */
export const phoneDinner: Lesson = {
  id: 'gj-08',
  badge: 'JLPT N3',
  listTitle: 'ちょうど今、鍋で材料を煮ているところ',
  listSummary: '朋友打电话约吃烤肉：你是正要做、正在做，还是刚做完？',
  image: {
    src: '/phone-dinner.png',
    alt: '左右分屏：左边男生站在夜晚的烤肉店门口打电话，店里朋友在招手；右边戴圆眼镜的女生在厨房里夹着手机，一边搅着冒热气的咖喱锅',
  },
  grammar: {
    title: '〜ところだ（三态）',
    summary: '说动作正处在哪个阶段：正要做、正在做、刚做完。',
    example: 'ちょうど今、鍋で材料を煮ているところ。',
    note: '动词辞书形 + ところだ 是「正要……」（今から出かけるところだ）；动词ている + ところだ 是「正在……」（今、料理をしているところだ）；动词た形 + ところだ 是「刚……完」（今、帰ってきたところだ）。三个形态说的是动作正处在哪个阶段，比单纯的 〜ている 更强调「正好在这个时点」，常用在打电话、回答「你现在在干嘛」的时候。〜たところ 只说「就在刚才」这个时点；一周前这种「感觉上没过多久」要用 〜たばかり，后面单独开课。',
    points: [
      '**辞书形 + ところだ**：正要……（今から出かけるところだ）',
      '**ている + ところだ**：正在……（今、料理をしているところだ）',
      '**た形 + ところだ**：刚……完（ちょうど帰ってきたところだ）',
      '说的是动作处在 **哪个阶段**，强调「正好在这个时点」',
      '常用在打电话、回答「你现在在干嘛」',
      '**〜たところ**＝就在刚才；一周前这种用 **〜たばかり**',
    ],
  },
  dialogue: [
    {
      role: 'A',
      text: 'もしもし、リン？ 今、何してる？',
      zh: '喂，小粼？在干嘛呢？',
      audio: `${AUDIO}/dialogue-01.m4a`,
    },
    {
      role: 'B',
      text: 'ちょうど今、鍋で材料を煮ているところ。どうしたの？',
      zh: '正在用锅煮菜呢。怎么了？',
      audio: `${AUDIO}/dialogue-02.m4a`,
    },
    {
      role: 'A',
      text: '偶然、駅前でゼミのみんなに会って、焼き肉を食べに行くことになったんだ。来ない？ 今から店に入るところ。',
      zh: '刚好在车站前碰到研讨课的大家，说好去吃烤肉。你来不来？我们正要进店。',
      audio: `${AUDIO}/dialogue-03.m4a`,
    },
    {
      role: 'B',
      text: 'えー、行きたい！ でも、せっかくカレーが出来上がったところなんだよね。',
      zh: '啊，想去！可是咖喱好不容易刚做好……',
      audio: `${AUDIO}/dialogue-04.m4a`,
    },
    {
      role: 'A',
      text: 'じゃあ、食べてから来たら？ まだ始まったところだから、ゆっくりでいいよ。',
      zh: '那吃完再来呗？这边才刚开始，慢慢来。',
      audio: `${AUDIO}/dialogue-05.m4a`,
    },
    {
      role: 'B',
      text: 'わかった。今から急いで食べるところだから、三十分後に合流するね。',
      zh: '好。我这就赶紧吃，三十分钟后跟你们会合。',
      audio: `${AUDIO}/dialogue-06.m4a`,
    },
  ],
  feeling: {
    eyebrow: '整体感觉',
    question: '電話が来たとき、リンは何をしていましたか。',
    choices: [
      { value: 'yakiniku', label: '焼き肉を食べていた' },
      { value: 'station', label: '駅に向かっていた' },
      { value: 'cooking', label: '晩ご飯を作っていた' },
      { value: 'sleeping', label: '寝ていた' },
    ],
    correct: 'cooking',
    success: '答对了。第 2 句：正在用锅煮菜（ているところ），后来咖喱刚做好（出来上がったところ）。',
    hint: '看第 2 句。',
  },
  meaning: {
    eyebrow: '语法原型',
    question: '「〜たところだ」は何を表す？',
    choices: [
      { value: 'before', label: 'これから〜する' },
      { value: 'during', label: '今〜している最中だ' },
      { value: 'exp', label: '〜したことがある' },
      { value: 'after', label: '〜が終わったばかりの時点だ' },
    ],
    correct: 'after',
    success: '答对了。「出来上がったところ」＝刚刚做好。正要做是辞书形 + ところ，正在做是 ている + ところ。',
    hint: '第 4 句：咖喱是还没做、正在做，还是刚做好？',
  },
  grammarTests: [
    {
      question: '把括号里的动词接上适合句子的形式。',
      full: '今から家を出るところです。',
      blank: '今から家を (出る) ______ ところです。',
      choices: ['出た', '出て', '出ていた', '出る'],
      correct: '出る',
      explain: '答对了。「今から」＝正要，用辞书形 + ところ。课文是朋友间的普通体，这里用丁寧語（です）。',
      zh: '我现在正要出门。',
    },
    {
      question: '「今、駅に着いたところです」に一番近い意味は？',
      full: '今、駅に着いたところです。',
      blank: '「…」 ______',
      choices: [
        'ほんの少し前に駅に着いた',
        'これから駅に行く',
        '駅に向かって歩いている',
        '駅に着いたことがある',
      ],
      correct: 'ほんの少し前に駅に着いた',
      explain: '答对了。た形 + ところ＝就在刚才做完。',
      zh: '我刚到车站。',
    },
    {
      question: '次の中で自然な文は？',
      full: '今、お風呂に入っているところなので、あとで電話します。',
      blank: '「…」 ______',
      choices: [
        '昨日、家に着いたところです。',
        '今、お風呂に入っているところなので、あとで電話します。',
        '来年、日本に行くところです。',
        '三年前に結婚したところです。',
      ],
      correct: '今、お風呂に入っているところなので、あとで電話します。',
      explain: '答对了。①④たところ 只能说「就在刚才」，昨天、三年前用不了；③很远的将来用 〜予定です、〜つもりです。',
      zh: '我正在洗澡，等会儿给你打电话。',
    },
  ],
  grammarTestHint: '不太对。正要＝辞书形 + ところ，正在＝ている + ところ，刚做完＝た形 + ところ。',
  errorTests: [
    {
      wrong: '今から出かけたところです。',
      fixed: '今から出かけるところです。',
      choices: [
        '「今から（これから）」は辞書形 + ところ。た形 + ところ は「したばかり」の意味になる',
        '今から は 今 にする',
        '出かけた は 出かけました にする',
        'ところです は ところだ にしなければならない',
      ],
      correct: '「今から（これから）」は辞書形 + ところ。た形 + ところ は「したばかり」の意味になる',
      explain: '「今から」是还没出门，用辞书形：出かけるところ。「出かけたところ」是刚出门。',
      zh: '我现在正要出门。',
    },
    {
      wrong: '今、晩ご飯を作るところだ。（想说「正在做」）',
      fixed: '今、晩ご飯を作っているところだ。',
      choices: [
        '晩ご飯 の後ろは が にする',
        '今 は 今から にする',
        '「している最中」は 〜ているところ。辞書形 + ところ は「これからする」',
        'だ は です にしなければならない',
      ],
      correct: '「している最中」は 〜ているところ。辞書形 + ところ は「これからする」',
      explain: '「作るところ」是正要做，还没开始。正在做要说「作っているところ」。',
      zh: '我正在做晚饭。',
    },
    {
      wrong: '先週、日本に来たところです。',
      fixed: '先週、日本に来たばかりです。',
      choices: [
        '先週 は 先週に にしなければならない',
        '〜たところ は「たった今」の時点だけ。一週間前なら 〜たばかり を使う',
        '来た は 来る にする',
        '日本に は 日本へ にしなければならない',
      ],
      correct: '〜たところ は「たった今」の時点だけ。一週間前なら 〜たばかり を使う',
      explain: '一周前已经不是「就在刚才」了。心里觉得「没过多久」，用 〜たばかり。',
      zh: '我上周刚来日本。',
    },
  ],
  lessonWords: [
    {
      ja: '鍋',
      zh: '锅；火锅',
      example: '寒い日は、家族で鍋を食べます。',
      audio: `${AUDIO}/lesson-01-example.m4a`,
      termAudio: `${AUDIO}/lesson-01-term.m4a`,
      quiz: '料理を煮たり、みんなで囲んで食べたりする深い器を「___」と言う。',
    },
    {
      ja: '材料',
      zh: '材料；食材',
      example: 'カレーの材料をスーパーで買いました。',
      audio: `${AUDIO}/lesson-02-example.m4a`,
      termAudio: `${AUDIO}/lesson-02-term.m4a`,
      quiz: '料理や物を作るのに使うものを「___」と言う。',
    },
    {
      ja: '偶然',
      zh: '偶然；碰巧',
      example: '駅で偶然、高校の先生に会いました。',
      audio: `${AUDIO}/lesson-03-example.m4a`,
      termAudio: `${AUDIO}/lesson-03-term.m4a`,
      quiz: '約束していないのに、たまたまそうなることを「___」と言う。',
    },
    {
      ja: 'せっかく',
      zh: '好不容易；特意',
      example: 'せっかく作ったのに、誰も食べてくれませんでした。',
      audio: `${AUDIO}/lesson-04-example.m4a`,
      termAudio: `${AUDIO}/lesson-04-term.m4a`,
      quiz: '時間や手間をかけたのだから、むだにしたくない、という気持ちで「___」と言う。',
    },
    {
      ja: '出来上がる',
      zh: '做好；完成',
      example: '新しい駅ビルが来月出来上がります。',
      audio: `${AUDIO}/lesson-05-example.m4a`,
      termAudio: `${AUDIO}/lesson-05-term.m4a`,
      quiz: '作っていたものが全部できることを「___」と言う。',
    },
    {
      ja: '合流する',
      zh: '会合；汇合',
      example: '仕事が終わったら、みんなと合流します。',
      audio: `${AUDIO}/lesson-06-example.m4a`,
      termAudio: `${AUDIO}/lesson-06-term.m4a`,
      quiz: '別々に来た人たちが途中から一緒になることを「___」と言う。',
    },
  ],
  bonusWords: [
    { ja: '誘う', zh: '邀请；约', example: '友達を映画に誘いました。', audio: `${AUDIO}/word-01-example.m4a`, termAudio: `${AUDIO}/word-01-term.m4a`, quiz: '一緒に何かをしようと声をかけることを「___」と言う。' },
    { ja: '断る', zh: '拒绝', example: '忙しかったので、飲み会の誘いを断りました。', audio: `${AUDIO}/word-02-example.m4a`, termAudio: `${AUDIO}/word-02-term.m4a`, quiz: '頼まれたことや誘いを受けないことを「___」と言う。' },
    { ja: '待ち合わせる', zh: '约好碰头', example: '駅の改札で七時に待ち合わせました。', audio: `${AUDIO}/word-03-example.m4a`, termAudio: `${AUDIO}/word-03-term.m4a`, quiz: '時間と場所を決めて会うことを「___」と言う。' },
    { ja: '遅刻する', zh: '迟到', example: '寝坊して、授業に遅刻しました。', audio: `${AUDIO}/word-04-example.m4a`, termAudio: `${AUDIO}/word-04-term.m4a`, quiz: '決まった時間に遅れて着くことを「___」と言う。' },
    { ja: '到着する', zh: '到达', example: '飛行機は予定より早く到着しました。', audio: `${AUDIO}/word-05-example.m4a`, termAudio: `${AUDIO}/word-05-term.m4a`, quiz: '目的の場所に着くことを「___」と言う。' },
    { ja: '集合する', zh: '集合', example: '明日は九時に駅の東口に集合してください。', audio: `${AUDIO}/word-06-example.m4a`, termAudio: `${AUDIO}/word-06-term.m4a`, quiz: '決まった場所に大勢が集まることを「___」と言う。' },
    { ja: '参加する', zh: '参加', example: '来週のパーティーに参加します。', audio: `${AUDIO}/word-07-example.m4a`, termAudio: `${AUDIO}/word-07-term.m4a`, quiz: '集まりや活動に加わることを「___」と言う。' },
    { ja: '飲み会', zh: '聚餐；酒会', example: '金曜日にクラスの飲み会があります。', audio: `${AUDIO}/word-08-example.m4a`, termAudio: `${AUDIO}/word-08-term.m4a`, quiz: 'みんなでお酒を飲みながら話す集まりを「___」と言う。' },
    { ja: '割り勘', zh: '平摊（费用）', example: '食事代は割り勘にしました。', audio: `${AUDIO}/word-09-example.m4a`, termAudio: `${AUDIO}/word-09-term.m4a`, quiz: '食事代などを人数で同じ額ずつ払うことを「___」と言う。' },
    { ja: 'おごる', zh: '请客', example: '今日は先輩がおごってくれました。', audio: `${AUDIO}/word-10-example.m4a`, termAudio: `${AUDIO}/word-10-term.m4a`, quiz: 'ほかの人の分のお金も払ってあげることを「___」と言う。' },
  ],
  sentence: {
    marker: '(る|た|ている|ていた|てる)ところ',
    markerNoSpace: '(る|た|ている)所',
    spacingLabel: '写法：ところ 用假名，没有写成「所」',
    displayName: '〜ところだ',
    meaningSide: 'before',
    meaningLabel: '句意完整：ところ 前面写出了在哪个阶段、做什么',
    starters: ['今から', 'ちょうど今', 'たった今'],
    placeholder: '例：ちょうど今、家に帰ってきたところです。',
  },
  sentenceTitle: '用 〜ところだ 说说你现在在干嘛',
  related: [
    { id: 'gj-10', note: '〜たばかり 按心里的感觉，上周、上个月也能用；〜たところ 只说「就在刚才那一刻」' },
  ],
};
