import type { Lesson } from './types';

const AUDIO = '/audio/standard/gj-02';

/**
 * 网站第 2 课：動詞て形 + もいいですか／てはいけません（许可与禁止）。JLPT N4。
 * 大纲 ~/Developer/nihongo/grammar/LESSON_DRAFT_gj-01-02.md（Luna 2026-09-27 拍板）。
 * 人物：A＝拓也（男，来看房，第 1 课那位）；B＝山本（女，房东，四十多岁）。
 * 语体：租客 ↔ 房东，丁寧語 → 练习第 1 题用普通体。
 */
export const roomViewing: Lesson = {
  id: 'gj-02',
  badge: 'JLPT N4',
  listTitle: '猫を飼ってもいいですか',
  listSummary: '看房时问房东：能挂画吗？能养猫吗？',
  image: {
    src: '/room-viewing.png',
    alt: '阳光照进空荡荡的单间公寓，年轻男生抬头看着墙壁发问，门口的房东笑着解释，男生脚边放着猫包',
  },
  grammar: {
    title: '動詞て形 + もいい／てはいけない',
    summary: '问「可以……吗」、答「可以／不行」。许可和禁止是一对。',
    example: '壁に絵を掛けてもいいですか。',
    note: '动词て形接 もいいですか 是请求许可（可以……吗）。回答可以说 〜てもいいですよ、どうぞ；回答不行说 〜てはいけません，或者委婉地说「ちょっと…」。〜てはいけません 语气硬，多见于规定和告示。普通体说 〜てもいい？、〜ちゃだめ。「不必」是另一个句型 〜なくてもいい，别和禁止混在一起。',
    points: [
      '许可：动词 **て形 + もいいですか**（可以……吗）',
      '回答可以：**〜てもいいですよ／どうぞ**',
      '禁止：动词 **て形 + はいけません**（语气硬，多见于规定）',
      '委婉拒绝：**ちょっと…／ちょっと困ります**',
      '普通体：**〜てもいい？／〜ちゃだめ**',
      '别和「不必」**〜なくてもいい** 混在一起',
    ],
  },
  dialogue: [
    {
      role: 'A',
      text: 'すみません、壁に絵を掛けてもいいですか。',
      zh: '请问，可以在墙上挂画吗？',
      audio: `${AUDIO}/dialogue-01.m4a`,
    },
    {
      role: 'B',
      text: 'ええ、小さい釘なら使ってもいいですよ。',
      zh: '可以，小钉子的话可以用。',
      audio: `${AUDIO}/dialogue-02.m4a`,
    },
    {
      role: 'A',
      text: 'ありがとうございます。あと、猫を飼ってもいいですか。',
      zh: '谢谢。还有，可以养猫吗？',
      audio: `${AUDIO}/dialogue-03.m4a`,
    },
    {
      role: 'B',
      text: 'すみません、この建物では動物を飼ってはいけないんです。',
      zh: '不好意思，这栋楼不能养动物。',
      audio: `${AUDIO}/dialogue-04.m4a`,
    },
    {
      role: 'A',
      text: 'そうですか…。じゃあ、友達を泊めてもいいですか。',
      zh: '这样啊……那可以留朋友过夜吗？',
      audio: `${AUDIO}/dialogue-05.m4a`,
    },
    {
      role: 'B',
      text: '二、三日ならかまいませんよ。それより長かったらちょっと困りますけどね。',
      zh: '两三天的话没关系。比那更久的话就有点为难了。',
      audio: `${AUDIO}/dialogue-06.m4a`,
    },
  ],
  feeling: {
    eyebrow: '整体感觉',
    question: 'この部屋でしてはいけないことは？',
    choices: [
      { value: 'animal', label: '動物を飼うこと' },
      { value: 'picture', label: '壁に絵を掛けること' },
      { value: 'friend', label: '友達を泊めること' },
      { value: 'nail', label: '小さい釘を使うこと' },
    ],
    correct: 'animal',
    success: '答对了。第 4 句：这栋楼不能养动物。挂画可以，朋友住两三天也可以。',
    hint: '看第 4 句。',
  },
  meaning: {
    eyebrow: '语法原型',
    question: '「〜てもいいですか」は何をするときに使う？',
    choices: [
      { value: 'request', label: '相手に何かを頼むとき' },
      { value: 'exp', label: '自分の経験を話すとき' },
      { value: 'permit', label: '相手に許可をもらいたいとき' },
      { value: 'invite', label: '相手を誘うとき' },
    ],
    correct: 'permit',
    success: '答对了。问的是「我可以做……吗」，要对方点头。请对方替自己做事是另一个句型（〜てください）。',
    hint: '第 3 句：拓也是想让房东做事，还是想问自己能不能做？',
  },
  grammarTests: [
    {
      question: '把括号里的动词接上适合句子的形式。',
      full: 'このパソコン、ちょっと使ってもいい？',
      blank: 'このパソコン、ちょっと (使う) ______？',
      choices: ['使うもいい', '使ってもいい', '使ったもいい', '使いもいい'],
      correct: '使ってもいい',
      explain: '答对了。动词先变成て形（使って），再接 もいい。跟朋友说话用普通体，句尾不加ですか。',
      zh: '这台电脑我能用一下吗？',
    },
    {
      question: '「ここで写真を撮ってはいけません」に一番近い意味は？',
      full: 'ここで写真を撮ってはいけません。',
      blank: '「…」 ______',
      choices: [
        'ここで写真を撮ってください',
        'ここで写真を撮らなくてもいいです',
        'ここで写真を撮ったほうがいいです',
        'ここで写真を撮ることは禁止です',
      ],
      correct: 'ここで写真を撮ることは禁止です',
      explain: '答对了。〜てはいけません 是禁止。「撮らなくてもいい」是「不拍也行」，意思不一样。',
      zh: '这里不能拍照。',
    },
    {
      question: '次の中で自然な文は？',
      full: '先生、教室で弁当を食べてもいいですか。',
      blank: '「…」 ______',
      choices: [
        '先生、教室で弁当を食べるもいいですか。',
        '先生、教室で弁当を食べてもいいましたか。',
        '先生、教室で弁当を食べてもいいですか。',
        '先生、教室で弁当を食べてはいいですか。',
      ],
      correct: '先生、教室で弁当を食べてもいいですか。',
      explain: '答对了。①动词没变て形；②いい 不能变成 いいました；④许可是 てもいい，不是 てはいい。',
      zh: '老师，可以在教室里吃便当吗？',
    },
  ],
  grammarTestHint: '不太对。动词先变成て形：许可接 もいい，禁止接 はいけない。',
  errorTests: [
    {
      wrong: '猫を飼うてもいいですか。',
      fixed: '猫を飼ってもいいですか。',
      choices: [
        '飼う は て形 にしてから もいい を付ける',
        '猫 の後ろは が にする',
        '飼う は 飼います にしなければならない',
        '質問には もいいですか が使えない',
      ],
      correct: '飼う は て形 にしてから もいい を付ける',
      explain: '飼う 的て形是 飼って（う 结尾的动词变成 って）。',
      zh: '可以养猫吗？',
    },
    {
      wrong: 'この建物では動物を飼わなくてもいいんです。（想说「不能养」）',
      fixed: 'この建物では動物を飼ってはいけないんです。',
      choices: [
        '建物 は ビル にする',
        '〜なくてもいい は「しなくても大丈夫」という意味で、禁止には 〜てはいけない を使う',
        '動物 の後ろは が にする',
        'んです は使えない',
      ],
      correct: '〜なくてもいい は「しなくても大丈夫」という意味で、禁止には 〜てはいけない を使う',
      explain: '「飼わなくてもいい」是「不养也可以」，意思完全不同。禁止要说「飼ってはいけない」。',
      zh: '这栋楼不能养动物。',
    },
    {
      wrong: '小さい釘なら使ってはいいですよ。',
      fixed: '小さい釘なら使ってもいいですよ。',
      choices: [
        '釘 は カタカナで書く',
        'なら は たら にする',
        '使って は 使う にする',
        '許可は 〜てもいい で、〜てはいい とは言わない',
      ],
      correct: '許可は 〜てもいい で、〜てはいい とは言わない',
      explain: '许可用 も：てもいい；禁止用 は：てはいけない。助词别弄反。',
      zh: '小钉子的话可以用。',
    },
  ],
  lessonWords: [
    {
      ja: '掛ける',
      zh: '挂',
      example: 'コートをハンガーに掛けました。',
      audio: `${AUDIO}/lesson-01-example.m4a`,
      termAudio: `${AUDIO}/lesson-01-term.m4a`,
      quiz: '壁やハンガーに物をつるすことを「___」と言う。',
    },
    {
      ja: '釘',
      zh: '钉子',
      example: '壁に釘を打ちました。',
      audio: `${AUDIO}/lesson-02-example.m4a`,
      termAudio: `${AUDIO}/lesson-02-term.m4a`,
      quiz: '木や壁に打って物を留める細い金属を「___」と言う。',
    },
    {
      ja: '飼う',
      zh: '养（动物）',
      example: '子どものころ、犬を飼っていました。',
      audio: `${AUDIO}/lesson-03-example.m4a`,
      termAudio: `${AUDIO}/lesson-03-term.m4a`,
      quiz: '家で動物の世話をして育てることを「___」と言う。',
    },
    {
      ja: '泊める',
      zh: '让（人）住宿',
      example: '週末、友達を家に泊めました。',
      audio: `${AUDIO}/lesson-04-example.m4a`,
      termAudio: `${AUDIO}/lesson-04-term.m4a`,
      quiz: '人を自分の家で一晩過ごさせることを「___」と言う。',
    },
    {
      ja: 'かまわない',
      zh: '没关系；不介意',
      example: '少し遅くなってもかまいません。',
      audio: `${AUDIO}/lesson-05-example.m4a`,
      termAudio: `${AUDIO}/lesson-05-term.m4a`,
      quiz: '「大丈夫です、気にしません」という意味の言葉は「___」だ。',
    },
    {
      ja: '困る',
      zh: '为难；伤脑筋',
      example: '急に言われても困ります。',
      audio: `${AUDIO}/lesson-06-example.m4a`,
      termAudio: `${AUDIO}/lesson-06-term.m4a`,
      quiz: 'どうしたらいいか分からなくて大変なことを「___」と言う。',
    },
  ],
  bonusWords: [
    { ja: '大家さん', zh: '房东', example: '大家さんに家賃を払いました。', audio: `${AUDIO}/word-01-example.m4a`, termAudio: `${AUDIO}/word-01-term.m4a`, quiz: 'アパートや家を貸している人を「___」と言う。' },
    { ja: '家賃', zh: '房租', example: '家賃は月に七万円です。', audio: `${AUDIO}/word-02-example.m4a`, termAudio: `${AUDIO}/word-02-term.m4a`, quiz: '部屋を借りて毎月払うお金を「___」と言う。' },
    { ja: '引っ越す', zh: '搬家', example: '来月、新しいアパートに引っ越します。', audio: `${AUDIO}/word-03-example.m4a`, termAudio: `${AUDIO}/word-03-term.m4a`, quiz: '住む所を変えることを「___」と言う。' },
    { ja: '部屋を探す', zh: '找房子', example: '駅の近くで部屋を探しています。', audio: `${AUDIO}/word-04-example.m4a`, termAudio: `${AUDIO}/word-04-term.m4a`, quiz: '住むための部屋を見つけようとすることを「___」と言う。' },
    { ja: '契約する', zh: '签约', example: '昨日、部屋の契約をしました。', audio: `${AUDIO}/word-05-example.m4a`, termAudio: `${AUDIO}/word-05-term.m4a`, quiz: '約束を書類にして正式に決めることを「___」と言う。' },
    { ja: '一人暮らし', zh: '一个人住', example: '大学から一人暮らしを始めました。', audio: `${AUDIO}/word-06-example.m4a`, termAudio: `${AUDIO}/word-06-term.m4a`, quiz: '家族と離れて一人で住むことを「___」と言う。' },
    { ja: '日当たり', zh: '采光', example: 'この部屋は日当たりがいいです。', audio: `${AUDIO}/word-07-example.m4a`, termAudio: `${AUDIO}/word-07-term.m4a`, quiz: '部屋に太陽の光が入る具合を「___」と言う。' },
    { ja: '騒音', zh: '噪音', example: '夜の騒音がひどいです。', audio: `${AUDIO}/word-08-example.m4a`, termAudio: `${AUDIO}/word-08-term.m4a`, quiz: 'うるさくて困る音を「___」と言う。' },
    { ja: 'ゴミを出す', zh: '扔垃圾', example: 'ゴミは火曜日に出します。', audio: `${AUDIO}/word-09-example.m4a`, termAudio: `${AUDIO}/word-09-term.m4a`, quiz: '決まった日にゴミを外に置くことを「___」と言う。' },
    { ja: '鍵をかける', zh: '锁门', example: '出かける前に鍵をかけました。', audio: `${AUDIO}/word-10-example.m4a`, termAudio: `${AUDIO}/word-10-term.m4a`, quiz: 'ドアが開かないようにすることを「___」と言う。' },
    { ja: '隣の人', zh: '邻居', example: '隣の人にあいさつしました。', audio: `${AUDIO}/word-11-example.m4a`, termAudio: `${AUDIO}/word-11-term.m4a`, quiz: 'すぐ横の部屋や家に住んでいる人を「___」と言う。' },
    { ja: '禁止', zh: '禁止', example: 'この公園はボール遊びが禁止です。', audio: `${AUDIO}/word-12-example.m4a`, termAudio: `${AUDIO}/word-12-term.m4a`, quiz: 'してはいけないと決まっていることを「___」と言う。' },
  ],
  sentence: {
    marker: '(て|で)(も|は)(いい|いけ|だめ|かまわ)',
    markerNoSpace: '(て|で)(も|は)(良い|駄目)',
    spacingLabel: '写法：いい・だめ 用假名，没有写成「良い」「駄目」',
    displayName: '〜てもいい／〜てはいけない',
    meaningSide: 'before',
    meaningLabel: '句意完整：てもいい 前面写出了想做什么',
    starters: ['ここで', 'この本を', '窓を'],
    placeholder: '例：窓を開けてもいいですか。',
  },
  sentenceTitle: '用 〜てもいい／〜てはいけない 问问看',
};
