import type { Lesson } from './types';

const AUDIO = '/audio/standard/gj-06';

/**
 * 网站第 6 课：〜すぎる（太……了）。JLPT N4。
 * 大纲 notes/LESSON_DRAFT_gj-05-06.md（Luna 2026-09-29「你刚给我的课文可以先做」）。
 * 人物：A＝拓也（男）；B＝リン（女，中国留学生）。大学同学。
 * 语体：N4 基础课一律丁寧語 → 练习第 1 题用普通体。
 */
export const spicyCurry: Lesson = {
  id: 'gj-06',
  badge: 'JLPT N4',
  listTitle: 'このカレー、辛すぎます',
  listSummary: '点了超辣大份咖喱：太辣、太多，还饿过头了。',
  image: {
    src: '/spicy-curry.png',
    alt: '小咖喱店里，男生对着一大盘红色的辣咖喱冒汗扇风，手里拿着水杯，对面戴圆眼镜的女生面前一小盘黄咖喱，正在笑',
  },
  grammar: {
    title: '〜すぎる',
    summary: '超过合适的程度：「太……了」，多半带着受不了的语气。',
    example: 'このカレー、辛すぎます。',
    note: 'い形容词去掉い接 すぎる（辛い→辛すぎる），な形容词去掉な接 すぎる（静か→静かすぎる），动词ます形去掉ます接 すぎる（食べます→食べすぎる）。意思是超过了合适的程度，多半带着「受不了、不好」的语气。すぎる 本身是一段动词，可以变成 すぎます、すぎました、すぎて。名词形 〜すぎ 也很常用（頼みすぎです）。いい 要变成 よすぎる。和 とても 分清：とても辛い 只是很辣，辛すぎる 是辣得受不了。',
    points: [
      '**い形容词**去い + すぎる（辛すぎる）；**な形容词**去な + すぎる（静かすぎる）',
      '**动词ます形**去ます + すぎる（食べすぎる、頼みすぎる）',
      '意思：**超过合适的程度**，多半带「受不了、不好」的语气',
      'すぎる 是一段动词：すぎます／すぎました／**すぎて**',
      '名词形 **〜すぎ**：頼みすぎです、食べすぎです',
      '特殊：**いい → よすぎる**；和 **とても**（只是程度高）分清',
    ],
  },
  dialogue: [
    {
      role: 'A',
      text: 'うわ、このカレー、辛すぎます。水、水…。',
      zh: '哇，这咖喱太辣了。水，水……',
      audio: `${AUDIO}/dialogue-01.m4a`,
    },
    {
      role: 'B',
      text: 'だから、「激辛は辛すぎますよ」と言いましたよね。',
      zh: '所以我不是说了「超辣的太辣了」嘛。',
      audio: `${AUDIO}/dialogue-02.m4a`,
    },
    {
      role: 'A',
      text: 'それに、大盛りも多すぎました。全部は食べられません。',
      zh: '而且大份也太多了。吃不完。',
      audio: `${AUDIO}/dialogue-03.m4a`,
    },
    {
      role: 'B',
      text: '拓也さんは、いつも頼みすぎですよ。',
      zh: '拓也你总是点太多。',
      audio: `${AUDIO}/dialogue-04.m4a`,
    },
    {
      role: 'A',
      text: 'すみません。おなかがすきすぎて、何も考えていませんでした。',
      zh: '对不起。饿过头了，什么都没想。',
      audio: `${AUDIO}/dialogue-05.m4a`,
    },
    {
      role: 'B',
      text: 'じゃあ、少し手伝います。私のは甘すぎるので、ちょうどいいです。',
      zh: '那我帮你吃一点吧。我的太甜了，正好。',
      audio: `${AUDIO}/dialogue-06.m4a`,
    },
  ],
  feeling: {
    eyebrow: '整体感觉',
    question: '拓也さんのカレーはどうでしたか。',
    choices: [
      { value: 'toomuch', label: '辛すぎて、量も多すぎた' },
      { value: 'sweet', label: '甘すぎた' },
      { value: 'justright', label: 'ちょうどよかった' },
      { value: 'little', label: '少なすぎた' },
    ],
    correct: 'toomuch',
    success: '答对了。第 1 句太辣，第 3 句大份也太多。太甜的是リン的咖喱。',
    hint: '看第 1 句和第 3 句。',
  },
  meaning: {
    eyebrow: '语法原型',
    question: '「〜すぎる」は何を表す？',
    choices: [
      { value: 'just', label: 'ちょうどいい程度だ' },
      { value: 'little', label: '普通より少しだけ〜だ' },
      { value: 'over', label: 'ちょうどいい程度を超えている' },
      { value: 'not', label: '全然〜ない' },
    ],
    correct: 'over',
    success: '答对了。辛すぎる＝辣得超过了能接受的程度。第 6 句的「ちょうどいい」正好相反。',
    hint: '第 6 句：两份咖喱一个太辣、一个太甜，混在一起变成了什么？',
  },
  grammarTests: [
    {
      question: '把括号里的形容词接上适合句子的形式。',
      full: 'このかばんは重すぎて、持てない。',
      blank: 'このかばんは (重い) ______、持てない。',
      choices: ['重いすぎて', '重すぎて', '重くすぎて', '重さすぎて'],
      correct: '重すぎて',
      explain: '答对了。い形容词去掉い（重）接 すぎる，再变成て形 すぎて。自言自语、跟朋友说话用普通体（持てない）。',
      zh: '这个包太重了，拿不动。',
    },
    {
      question: '「昨日はお酒を飲みすぎました」に一番近い意味は？',
      full: '昨日はお酒を飲みすぎました。',
      blank: '「…」 ______',
      choices: [
        '昨日はちょうどいい量のお酒を飲んだ',
        '昨日はお酒を飲みたくなかった',
        '昨日はお酒を飲んではいけなかった',
        '昨日はいつもよりたくさん飲んで、よくなかった',
      ],
      correct: '昨日はいつもよりたくさん飲んで、よくなかった',
      explain: '答对了。飲みすぎる＝喝得超过了合适的量，带着「不好、后悔」的语气。',
      zh: '昨天酒喝多了。',
    },
    {
      question: '次の中で自然な文は？',
      full: 'このテストは簡単すぎて、みんな百点でした。',
      blank: '「…」 ______',
      choices: [
        '今日は暑すぎて、とても気持ちがいいです。',
        'この部屋は静かすぎるので、よく眠れました。',
        'このテストは簡単すぎて、みんな百点でした。',
        'ちょうどいい量すぎて、全部食べました。',
      ],
      correct: 'このテストは簡単すぎて、みんな百点でした。',
      explain: '答对了。①②すぎる 带「受不了」的语气，后面接好事不自然；④ちょうどいい 和 すぎる 意思矛盾。',
      zh: '这次考试太简单了，大家都考了一百分。',
    },
  ],
  grammarTestHint: '不太对。い形容词去い、动词ます形去ます，再接 すぎる。',
  errorTests: [
    {
      wrong: 'このカレーは辛いすぎます。',
      fixed: 'このカレーは辛すぎます。',
      choices: [
        'カレー は ひらがなで書く',
        'すぎます は すぎました にしなければならない',
        'この は その にする',
        'い形容詞は い を取ってから すぎる を付ける',
      ],
      correct: 'い形容詞は い を取ってから すぎる を付ける',
      explain: '辛い 去掉い 是 辛，再接 すぎます：辛すぎます。',
      zh: '这咖喱太辣了。',
    },
    {
      wrong: '拓也さんは、いつも頼むすぎですよ。',
      fixed: '拓也さんは、いつも頼みすぎですよ。',
      choices: [
        '動詞は ます形（頼み）にしてから すぎ を付ける',
        'いつも は よく にする',
        '拓也さんは は 拓也さんが にする',
        'ですよ は です にしなければならない',
      ],
      correct: '動詞は ます形（頼み）にしてから すぎ を付ける',
      explain: '頼む 的ます形是 頼みます，去掉ます 接 すぎ：頼みすぎ。',
      zh: '拓也你总是点太多。',
    },
    {
      wrong: 'この部屋は日当たりがいいすぎます。',
      fixed: 'この部屋は日当たりがよすぎます。',
      choices: [
        '日当たり は 日当り と書く',
        'いい は よ にしてから すぎる を付ける（いいすぎる とは言わない）',
        'この部屋は は この部屋が にする',
        'すぎます は すぎる にする',
      ],
      correct: 'いい は よ にしてから すぎる を付ける（いいすぎる とは言わない）',
      explain: 'いい 变形时用 よい 的词干：よすぎる。「いいすぎる」听起来像「言いすぎる」（说过头了）。',
      zh: '这个房间采光太好了。',
    },
  ],
  lessonWords: [
    {
      ja: '大盛り',
      zh: '大份',
      example: 'ご飯は大盛りでお願いします。',
      audio: `${AUDIO}/lesson-01-example.m4a`,
      termAudio: `${AUDIO}/lesson-01-term.m4a`,
      quiz: 'ご飯や料理の量をいつもより多くすることを「___」と言う。',
    },
    {
      ja: '頼む',
      zh: '点（菜）；拜托',
      example: '飲み物は何を頼みますか。',
      audio: `${AUDIO}/lesson-02-example.m4a`,
      termAudio: `${AUDIO}/lesson-02-term.m4a`,
      quiz: '店で料理を持ってきてもらうように言うことを「___」と言う。',
    },
    {
      ja: 'おなかがすく',
      zh: '肚子饿',
      example: '朝ご飯を食べなかったので、おなかがすきました。',
      audio: `${AUDIO}/lesson-03-example.m4a`,
      termAudio: `${AUDIO}/lesson-03-term.m4a`,
      quiz: '何か食べたいと感じることを「___」と言う。',
    },
    {
      ja: '手伝う',
      zh: '帮忙',
      example: '引っ越しを友達に手伝ってもらいました。',
      audio: `${AUDIO}/lesson-04-example.m4a`,
      termAudio: `${AUDIO}/lesson-04-term.m4a`,
      quiz: '人の仕事を一緒にしてあげることを「___」と言う。',
    },
    {
      ja: 'ちょうどいい',
      zh: '正好；刚刚好',
      example: 'このお風呂はちょうどいい温度です。',
      audio: `${AUDIO}/lesson-05-example.m4a`,
      termAudio: `${AUDIO}/lesson-05-term.m4a`,
      quiz: '多すぎず少なすぎず、ぴったりなことを「___」と言う。',
    },
  ],
  bonusWords: [
    { ja: '注文する', zh: '点菜；订购', example: 'ラーメンとギョーザを注文しました。', audio: `${AUDIO}/word-01-example.m4a`, termAudio: `${AUDIO}/word-01-term.m4a`, quiz: '店で料理や品物を頼むことを「___」と言う。' },
    { ja: 'メニュー', zh: '菜单', example: 'メニューを見せてください。', audio: `${AUDIO}/word-02-example.m4a`, termAudio: `${AUDIO}/word-02-term.m4a`, quiz: '店の料理の名前と値段が書いてある物を「___」と言う。' },
    { ja: '定食', zh: '套餐', example: '昼はいつも魚の定食を食べます。', audio: `${AUDIO}/word-03-example.m4a`, termAudio: `${AUDIO}/word-03-term.m4a`, quiz: 'ご飯とみそ汁とおかずがセットになった食事を「___」と言う。' },
    { ja: '食べ放題', zh: '自助餐；随便吃', example: 'この店は二千円で食べ放題です。', audio: `${AUDIO}/word-04-example.m4a`, termAudio: `${AUDIO}/word-04-term.m4a`, quiz: '決まったお金で好きなだけ食べられることを「___」と言う。' },
    { ja: '苦い', zh: '苦', example: 'このコーヒーは少し苦いです。', audio: `${AUDIO}/word-05-example.m4a`, termAudio: `${AUDIO}/word-05-term.m4a`, quiz: '薬やコーヒーのような味を「___」と言う。' },
    { ja: 'しょっぱい', zh: '咸', example: 'このスープはちょっとしょっぱいです。', audio: `${AUDIO}/word-06-example.m4a`, termAudio: `${AUDIO}/word-06-term.m4a`, quiz: '塩が多い味を「___」と言う。' },
    { ja: 'おかわり', zh: '再来一碗', example: 'ご飯のおかわりは無料です。', audio: `${AUDIO}/word-07-example.m4a`, termAudio: `${AUDIO}/word-07-term.m4a`, quiz: '食べ終わって、同じ物をもう一杯もらうことを「___」と言う。' },
    { ja: 'お会計', zh: '结账', example: 'すみません、お会計をお願いします。', audio: `${AUDIO}/word-08-example.m4a`, termAudio: `${AUDIO}/word-08-term.m4a`, quiz: '店で食べたあとにお金を払うことを「___」と言う。' },
    { ja: '飲み物', zh: '饮料', example: '飲み物は何にしますか。', audio: `${AUDIO}/word-09-example.m4a`, termAudio: `${AUDIO}/word-09-term.m4a`, quiz: 'お茶やジュースなど、飲む物を「___」と言う。' },
    { ja: '残す', zh: '剩下', example: '多かったので、少し残しました。', audio: `${AUDIO}/word-10-example.m4a`, termAudio: `${AUDIO}/word-10-term.m4a`, quiz: '全部食べないで、少し置いておくことを「___」と言う。' },
    { ja: '冷める', zh: '变凉', example: '話していたら、スープが冷めました。', audio: `${AUDIO}/word-11-example.m4a`, termAudio: `${AUDIO}/word-11-term.m4a`, quiz: '温かい物が冷たくなることを「___」と言う。' },
    { ja: '温める', zh: '加热', example: 'お弁当を電子レンジで温めます。', audio: `${AUDIO}/word-12-example.m4a`, termAudio: `${AUDIO}/word-12-term.m4a`, quiz: '冷たい物を温かくすることを「___」と言う。' },
  ],
  sentence: {
    marker: 'すぎ',
    markerNoSpace: '過ぎ',
    spacingLabel: '写法：すぎる 用假名，没有写成「過ぎる」',
    displayName: '〜すぎる',
    meaningSide: 'before',
    meaningLabel: '句意完整：すぎる 前面写出了什么太……',
    starters: ['この部屋は', '昨日は', 'この問題は'],
    placeholder: '例：この問題は難しすぎます。',
  },
  sentenceTitle: '用 〜すぎる 说说看',
};
