import type { Lesson } from './types';

const AUDIO = '/audio/standard/gj-07';

/**
 * N3 第 1 课：〜ばかり（净是……、老是光做……）。JLPT N3。
 * 大纲 notes/LESSON_DRAFT_gj-07-08.md（Luna 2026-09-29「N3 两课你可以先做」；单词已按等级筛过）。
 * 人物：A＝拓也（男）；B＝リン（女，中国留学生）。朋友。
 * 语体：N3 起课文回到默认值 → 朋友之间普通体；练习第 1 题用丁寧語。
 */
export const supermarketNoodles: Lesson = {
  id: 'gj-07',
  badge: 'JLPT N3',
  listTitle: '最近、カップラーメンばかり食べてるよね',
  listSummary: '超市里篮子装满杯面，被朋友吐槽「你老是光……」。',
  image: {
    src: '/supermarket-noodles.png',
    alt: '傍晚的超市货架间，男生得意地举着装满杯面的购物篮，旁边戴圆眼镜的女生提着一篮蔬菜，挑着眉看他',
  },
  grammar: {
    title: '〜ばかり',
    summary: '「净是……」「老是光做……」，多半带着不满、批评的语气。',
    example: '最近、カップラーメンばかり食べてるよね。',
    note: '名词后面加 ばかり，是「净是、光……」（カップラーメンばかり食べる）；动词て形加 ばかりいる，是「老是光做……」（遊んでばかりいる），口语里常说 〜てばかりだ、〜てばっかり。多半带着不满、批评的语气。ばかり 会替换掉 を・が，不能说「カップラーメンをばかり」。和 だけ 分清：だけ 只是客观地限定数量（一つだけ），ばかり 强调多、反复，带评价。〜たばかり（刚刚……）是另一个语法，后面单独开课。',
    points: [
      '**名词 + ばかり**：净是……、光……（カップラーメンばかり食べる）',
      '**动词て形 + ばかりいる**：老是光做……（遊んでばかりいる）',
      '语气：多半带着 **不满、批评**',
      '助词：ばかり **替换 を／が**（✗ カップラーメンをばかり）',
      '和 **だけ** 分清：だけ＝客观限定「只有」；ばかり＝「净是、老是」',
      '〜**た**ばかり（刚刚……）是另一个语法，后面单独开课',
    ],
  },
  dialogue: [
    {
      role: 'A',
      text: 'リン、見て。今週はカップラーメンが安いんだ。',
      zh: '小林你看，这周杯面便宜。',
      audio: `${AUDIO}/dialogue-01.m4a`,
    },
    {
      role: 'B',
      text: 'また？ 拓也、最近カップラーメンばかり食べてるよね。栄養が偏るよ。',
      zh: '又来？拓也你最近光吃杯面吧。营养会不均衡的。',
      audio: `${AUDIO}/dialogue-02.m4a`,
    },
    {
      role: 'A',
      text: '試験の前は忙しくて、自炊する暇がないんだよ。',
      zh: '考试前太忙了，没空自己做饭嘛。',
      audio: `${AUDIO}/dialogue-03.m4a`,
    },
    {
      role: 'B',
      text: '忙しいって言うけど、結局昨日もゲームしてばかりだったじゃない。',
      zh: '你说忙，结果昨天不也是光打游戏吗？',
      audio: `${AUDIO}/dialogue-04.m4a`,
    },
    {
      role: 'A',
      text: 'それは……息抜きだよ。リンだって、最近スマホばかり見てるよ。',
      zh: '那是……放松一下嘛。小林你最近不也光看手机。',
      audio: `${AUDIO}/dialogue-05.m4a`,
    },
    {
      role: 'B',
      text: '私は日本語のニュースを読んでるの。遊んでばかりの人と一緒にしないで。',
      zh: '我是在看日语新闻。别把我跟光知道玩的人混为一谈。',
      audio: `${AUDIO}/dialogue-06.m4a`,
    },
  ],
  feeling: {
    eyebrow: '整体感觉',
    question: 'リンは拓也の何が問題だと言っていますか。',
    choices: [
      { value: 'cook', label: '料理が下手なこと' },
      { value: 'news', label: '日本語のニュースを読まないこと' },
      { value: 'noodles', label: 'カップラーメンばかり食べて、ゲームばかりしていること' },
      { value: 'super', label: 'スーパーに来ないこと' },
    ],
    correct: 'noodles',
    success: '答对了。第 2 句说他光吃杯面，第 4 句说他光打游戏。',
    hint: '看第 2 句和第 4 句，リン用 ばかり 说了拓也什么？',
  },
  meaning: {
    eyebrow: '语法原型',
    question: '「〜てばかりいる」は何を表す？',
    choices: [
      { value: 'justnow', label: 'ちょうど今終わったところだ' },
      { value: 'always', label: '同じことばかりしていて、ほかのことをしない（あまりよくない）' },
      { value: 'once', label: '一回だけした' },
      { value: 'plan', label: 'これからする予定だ' },
    ],
    correct: 'always',
    success: '答对了。「ゲームしてばかり」＝老是光打游戏，别的事不做，带着批评的语气。',
    hint: '第 4 句：リン是在夸拓也，还是在说他不好？',
  },
  grammarTests: [
    {
      question: '把括号里的动词接上适合句子的形式。',
      full: '弟は毎日遊んでばかりいます。',
      blank: '弟は毎日 (遊ぶ) ______ います。',
      choices: ['遊ぶばかり', '遊びばかり', '遊んだばかり', '遊んでばかり'],
      correct: '遊んでばかり',
      explain: '答对了。遊ぶ 的て形是 遊んで，接 ばかりいる。「遊んだばかり」是「刚玩完」，意思不一样。课文是朋友间的普通体，这里用丁寧語（います）。',
      zh: '弟弟每天光知道玩。',
    },
    {
      question: '「最近、雨ばかりだね」に一番近い意味は？',
      full: '最近、雨ばかりだね。',
      blank: '「…」 ______',
      choices: [
        '最近、雨の日がとても多い',
        '最近、雨が一回だけ降った',
        '最近、雨が少ない',
        '最近、雨がちょうどやんだ',
      ],
      correct: '最近、雨の日がとても多い',
      explain: '答对了。雨ばかり＝净是下雨天，言外之意是「烦死了」。',
      zh: '最近老是下雨啊。',
    },
    {
      question: '次の中で自然な文は？',
      full: '冷蔵庫には、ビールばかり入っている。',
      blank: '「…」 ______',
      choices: [
        'テストは一問ばかり間違えた。',
        '明日ばかり休みます。',
        '冷蔵庫には、ビールばかり入っている。',
        'このケーキは甘いばかりおいしい。',
      ],
      correct: '冷蔵庫には、ビールばかり入っている。',
      explain: '答对了。①②客观地说「只有一道题、只有明天」用 だけ；④ばかり 不能这样连接两个形容词。',
      zh: '冰箱里全是啤酒。',
    },
  ],
  grammarTestHint: '不太对。名词直接接 ばかり，动词用て形接 ばかりいる；客观地说「只有」用 だけ。',
  errorTests: [
    {
      wrong: '拓也は毎日ゲームをするばかりいる。',
      fixed: '拓也は毎日ゲームをしてばかりいる。',
      choices: [
        '毎日 は 毎日に にする',
        'ゲーム は カタカナで書かない',
        'いる は ある にしなければならない',
        'する は て形（して）にしてから ばかりいる を付ける',
      ],
      correct: 'する は て形（して）にしてから ばかりいる を付ける',
      explain: '「老是光做」是动词て形 + ばかりいる：する→して→してばかりいる。',
      zh: '拓也每天光打游戏。',
    },
    {
      wrong: '最近カップラーメンをばかり食べている。',
      fixed: '最近カップラーメンばかり食べている。',
      choices: [
        '最近 は 最近に にする',
        'ばかり は を の代わりに入る。を と一緒に使わない',
        '食べている は 食べた にしなければならない',
        'カップラーメン は ラーメン にする',
      ],
      correct: 'ばかり は を の代わりに入る。を と一緒に使わない',
      explain: 'ばかり 顶替了 を 的位置，「カップラーメンばかり食べる」，不说「をばかり」。',
      zh: '最近光吃杯面。',
    },
    {
      wrong: '残っているケーキは一つばかりだ。（想说「只剩一个」）',
      fixed: '残っているケーキは一つだけだ。',
      choices: [
        '数を客観的に限る「只有」は だけ。ばかり は「多い・何度も」という気持ち',
        '残っている は 残る にする',
        'ケーキ の後ろは を にする',
        'だ は です にしなければならない',
      ],
      correct: '数を客観的に限る「只有」は だけ。ばかり は「多い・何度も」という気持ち',
      explain: '「只剩一个」是客观的数量，用 だけ。ばかり 是「净是、老是」，意思反而是多。',
      zh: '剩下的蛋糕只有一个。',
    },
  ],
  lessonWords: [
    {
      ja: '栄養',
      zh: '营养',
      example: '野菜は栄養がたくさんあります。',
      audio: `${AUDIO}/lesson-01-example.m4a`,
      termAudio: `${AUDIO}/lesson-01-term.m4a`,
      quiz: '体を元気にするために食べ物から取るものを「___」と言う。',
    },
    {
      ja: '偏る',
      zh: '偏（于一方）；不均衡',
      example: '外食ばかりだと、栄養が偏ります。',
      audio: `${AUDIO}/lesson-02-example.m4a`,
      termAudio: `${AUDIO}/lesson-02-term.m4a`,
      quiz: 'バランスが悪く、一つの方にばかり寄ることを「___」と言う。',
    },
    {
      ja: '自炊する',
      zh: '自己做饭',
      example: '一人暮らしを始めてから、毎日自炊しています。',
      audio: `${AUDIO}/lesson-03-example.m4a`,
      termAudio: `${AUDIO}/lesson-03-term.m4a`,
      quiz: '外で食べないで、自分でご飯を作ることを「___」と言う。',
    },
    {
      ja: '結局',
      zh: '结果；到头来',
      example: '一時間話したが、結局何も決まりませんでした。',
      audio: `${AUDIO}/lesson-04-example.m4a`,
      termAudio: `${AUDIO}/lesson-04-term.m4a`,
      quiz: 'いろいろあったが、最後はこうなった、と言うときに「___」を使う。',
    },
    {
      ja: '息抜き',
      zh: '喘口气；放松一下',
      example: '息抜きに、近くの公園を散歩しました。',
      audio: `${AUDIO}/lesson-05-example.m4a`,
      termAudio: `${AUDIO}/lesson-05-term.m4a`,
      quiz: '勉強や仕事の間に少し休んで気分を変えることを「___」と言う。',
    },
    {
      ja: '一緒にする',
      zh: '混为一谈；相提并论',
      example: '子どもの遊びと大人の仕事を一緒にしないでください。',
      audio: `${AUDIO}/lesson-06-example.m4a`,
      termAudio: `${AUDIO}/lesson-06-term.m4a`,
      quiz: '違うものを同じだと考えることを「___」と言う。',
    },
  ],
  bonusWords: [
    { ja: '健康', zh: '健康', example: '健康のために、毎朝歩いています。', audio: `${AUDIO}/word-01-example.m4a`, termAudio: `${AUDIO}/word-01-term.m4a`, quiz: '体も心も元気で、病気がない様子を「___」と言う。' },
    { ja: '夜更かし', zh: '熬夜', example: '夜更かしをして、朝起きられませんでした。', audio: `${AUDIO}/word-02-example.m4a`, termAudio: `${AUDIO}/word-02-term.m4a`, quiz: '夜遅くまで起きていることを「___」と言う。' },
    { ja: '寝不足', zh: '睡眠不足', example: '寝不足で、授業中に眠くなりました。', audio: `${AUDIO}/word-03-example.m4a`, termAudio: `${AUDIO}/word-03-term.m4a`, quiz: '寝る時間が足りないことを「___」と言う。' },
    { ja: '運動不足', zh: '缺乏运动', example: '車で通勤するようになって、運動不足です。', audio: `${AUDIO}/word-04-example.m4a`, termAudio: `${AUDIO}/word-04-term.m4a`, quiz: '体を動かすことが足りないことを「___」と言う。' },
    { ja: 'だらだらする', zh: '懒懒散散', example: '休みの日は、家でだらだらしてしまいます。', audio: `${AUDIO}/word-05-example.m4a`, termAudio: `${AUDIO}/word-05-term.m4a`, quiz: 'やる気がなく、何もしないで時間を過ごすことを「___」と言う。' },
    { ja: '節約する', zh: '节约', example: '旅行のために、お金を節約しています。', audio: `${AUDIO}/word-06-example.m4a`, termAudio: `${AUDIO}/word-06-term.m4a`, quiz: 'お金や物をむだに使わないようにすることを「___」と言う。' },
    { ja: '外食', zh: '在外面吃饭', example: '忙しい日は、つい外食になります。', audio: `${AUDIO}/word-07-example.m4a`, termAudio: `${AUDIO}/word-07-term.m4a`, quiz: '家ではなく、店で食事をすることを「___」と言う。' },
    { ja: '怠ける', zh: '偷懒', example: '勉強を怠けて、先生に注意されました。', audio: `${AUDIO}/word-08-example.m4a`, termAudio: `${AUDIO}/word-08-term.m4a`, quiz: 'しなければならないことをしないで、さぼることを「___」と言う。' },
    { ja: '反省する', zh: '反省', example: '遅刻したことを反省しています。', audio: `${AUDIO}/word-09-example.m4a`, termAudio: `${AUDIO}/word-09-term.m4a`, quiz: '自分のよくなかったことを考えて、次はしないと思うことを「___」と言う。' },
    { ja: '我慢する', zh: '忍耐；克制', example: 'ダイエット中なので、甘い物を我慢しています。', audio: `${AUDIO}/word-10-example.m4a`, termAudio: `${AUDIO}/word-10-term.m4a`, quiz: 'したいことや苦しいことを、じっと耐えることを「___」と言う。' },
  ],
  sentence: {
    marker: '(ばかり|ばっかり)',
    markerNoSpace: '許り',
    spacingLabel: '写法：ばかり 用假名，没有写成「許り」',
    displayName: '〜ばかり',
    meaningSide: 'before',
    meaningLabel: '句意完整：ばかり 前面写出了净是什么、老是做什么',
    starters: ['最近', '弟は', 'この店は'],
    placeholder: '例：弟は毎日ゲームをしてばかりいる。',
  },
  sentenceTitle: '用 〜ばかり 吐槽一下',
};
