import type { Lesson } from './types';

const AUDIO = '/audio/standard/gj-04';

/**
 * 网站第 4 课：〜たり〜たりします（举几个例子）。JLPT N4。
 * 大纲 notes/LESSON_DRAFT_gj-03-04.md（Luna 2026-09-29 拍板「开做」）。
 * 人物：A＝拓也（男）；B＝リン（女，中国留学生）。大学同学。
 * 语体：N4 基础课一律丁寧語 → 练习第 1 题用普通体。
 */
export const weekendTalk: Lesson = {
  id: 'gj-04',
  badge: 'JLPT N4',
  listTitle: '週末は何をしましたか',
  listSummary: '周一早上聊周末：逛街、看电影……其实一直在睡觉？',
  image: {
    src: '/weekend-talk.png',
    alt: '周一早上明亮的大学食堂，男生不好意思地挠着后脑勺，对面戴圆眼镜的女生捂着嘴笑，桌上放着两杯咖啡和吐司',
  },
  grammar: {
    title: '〜たり〜たりする',
    summary: '举几个例子说「又……又……之类的」，言外之意是还做了别的。',
    example: '友達と買い物をしたり、映画を見たりしました。',
    note: '动词た形加 り，两个排在一起，最后加 する：買い物をしたり、映画を見たりしました（読む 的た形是 読んだ，所以说 読んだり）。意思是举几个例子，还做了别的；按顺序把做过的事全说完要用 〜て、〜て。时态和礼貌体都放在最后的 する 上（しました、します、しています），前面的 たり 永远用た形。最后的 する 不能丢，たり 也要成对。两个相反的动作放在一起（食べたり寝たり、行ったり来たり）是「来回反复」。',
    points: [
      '形：动词 **た形 + り**，两个排在一起，最后加 **する**',
      '意思：**举几个例子**，还做了别的；按顺序全说完用 **〜て、〜て**',
      '时态、礼貌体放在最后的 **する** 上：〜たり〜たり**しました**',
      '最后的 **する 不能丢**，たり 要成对',
      '只举一个也行：本を読んだり**します**（看看书什么的）',
      '相反的动作：**食べたり寝たり**、**行ったり来たり**＝来回反复',
    ],
  },
  dialogue: [
    {
      role: 'A',
      text: 'リンさん、週末は何をしましたか。',
      zh: '小林，周末干什么了？',
      audio: `${AUDIO}/dialogue-01.m4a`,
    },
    {
      role: 'B',
      text: '友達と買い物をしたり、映画を見たりしました。拓也さんは？',
      zh: '和朋友逛了逛街、看了看电影。拓也你呢？',
      audio: `${AUDIO}/dialogue-02.m4a`,
    },
    {
      role: 'A',
      text: '僕は家で掃除をしたり、洗濯をしたりしていました。',
      zh: '我在家打扫打扫、洗洗衣服。',
      audio: `${AUDIO}/dialogue-03.m4a`,
    },
    {
      role: 'B',
      text: 'えらいですね。私は週末、部屋の掃除をあまりしません。',
      zh: '真勤快啊。我周末不太打扫房间。',
      audio: `${AUDIO}/dialogue-04.m4a`,
    },
    {
      role: 'A',
      text: '実は、ゲームをしたり寝たりしている時間のほうが長かったんです。',
      zh: '其实，打游戏、睡觉的时间更长。',
      audio: `${AUDIO}/dialogue-05.m4a`,
    },
    {
      role: 'B',
      text: 'やっぱり。私も日曜日は一日中、食べたり寝たりしていました。',
      zh: '我就知道。我星期天也是一整天光吃了睡、睡了吃。',
      audio: `${AUDIO}/dialogue-06.m4a`,
    },
  ],
  feeling: {
    eyebrow: '整体感觉',
    question: '拓也さんが週末、本当に長くしていたことは？',
    choices: [
      { value: 'clean', label: '掃除や洗濯' },
      { value: 'shopping', label: '買い物や映画' },
      { value: 'cook', label: '料理や散歩' },
      { value: 'game', label: 'ゲームや寝ること' },
    ],
    correct: 'game',
    success: '答对了。第 5 句：拓也先说打扫、洗衣服，其实打游戏、睡觉的时间更长。',
    hint: '看第 5 句，「実は」后面说了什么？',
  },
  meaning: {
    eyebrow: '语法原型',
    question: '「〜たり〜たりする」は何を表す？',
    choices: [
      { value: 'same', label: '二つのことを同時にする' },
      { value: 'examples', label: 'いくつかの例を挙げて言う' },
      { value: 'order', label: 'したことを順番に全部言う' },
      { value: 'exp', label: '自分の経験を言う' },
    ],
    correct: 'examples',
    success: '答对了。たり 是举例子：拓也说了打扫、洗衣服，其实还打了游戏、睡了觉。',
    hint: '第 3 句和第 5 句：拓也第一次说的是他周末做的全部事情吗？',
  },
  grammarTests: [
    {
      question: '把括号里的动词接上适合句子的形式。',
      full: '昨日は本を読んだり、音楽を聞いたりした。',
      blank: '昨日は本を (読む) ______、音楽を聞いたりした。',
      choices: ['読むたり', '読みたり', '読んだり', '読んたり'],
      correct: '読んだり',
      explain: '答对了。読む 的た形是 読んだ，加 り：読んだり。跟朋友说话用普通体（した）。',
      zh: '昨天看看书、听听音乐。',
    },
    {
      question: '「休みの日は料理をしたり、散歩をしたりします」に一番近い意味は？',
      full: '休みの日は料理をしたり、散歩をしたりします。',
      blank: '「…」 ______',
      choices: [
        '休みの日は料理をしながら散歩する',
        '休みの日は料理と散歩しかしない',
        '休みの日は料理をしてから、必ず散歩する',
        '休みの日は料理や散歩などをする',
      ],
      correct: '休みの日は料理や散歩などをする',
      explain: '答对了。たり 是举例：做饭、散步之类的，也可能做别的。不是同时做，也不是只做这两件、按顺序做。',
      zh: '休息日做做饭、散散步。',
    },
    {
      question: '次の中で自然な文は？',
      full: '電車の中では、音楽を聞いたり本を読んだりします。',
      blank: '「…」 ______',
      choices: [
        '電車の中では、音楽を聞いたり本を読んだりします。',
        '毎朝、七時に起きたり、七時半に家を出たりします。',
        '昨日は宿題をしたり、それから寝ました。',
        'このケーキは甘かったり、おいしいです。',
      ],
      correct: '電車の中では、音楽を聞いたり本を読んだりします。',
      explain: '答对了。②每天固定按顺序做的事用 起きて、家を出ます；③たり 不成对，也不能接「それから」；④想说「又甜又好吃」用 甘くて、おいしいです。',
      zh: '在电车里听听音乐、看看书。',
    },
  ],
  grammarTestHint: '不太对。动词变成た形再加 り，两个排在一起，最后加 する。',
  errorTests: [
    {
      wrong: '友達と映画を見るたり、買い物をするたりしました。',
      fixed: '友達と映画を見たり、買い物をしたりしました。',
      choices: [
        '映画を は 映画が にする',
        'たり は一回しか使えない',
        '見る・する は た形 にしてから り を付ける',
        'しました は します にする',
      ],
      correct: '見る・する は た形 にしてから り を付ける',
      explain: 'たり 接在た形后面：見る→見たり、する→したり。',
      zh: '和朋友看了看电影、逛了逛街。',
    },
    {
      wrong: '週末は掃除をしたり、洗濯をしました。',
      fixed: '週末は掃除をしたり、洗濯をしたりしました。',
      choices: [
        'たり は二つ並べて、最後に する を付ける',
        '掃除 は ひらがなで書く',
        '週末は は 週末に にしなければならない',
        '洗濯をしました は 洗濯しました にする',
      ],
      correct: 'たり は二つ並べて、最後に する を付ける',
      explain: '只有一个 たり，句子就半截了。两件事都用 たり，最后加 しました。',
      zh: '周末打扫打扫、洗洗衣服。',
    },
    {
      wrong: '週末は買い物をしましたり、映画を見ましたりしました。',
      fixed: '週末は買い物をしたり、映画を見たりしました。',
      choices: [
        '映画を は 映画に にする',
        'ました は最後の する にだけ付けて、たり の前は た形 にする',
        '買い物 は カタカナで書く',
        '週末は は要らない',
      ],
      correct: 'ました は最後の する にだけ付けて、たり の前は た形 にする',
      explain: '礼貌体只放在最后的 する 上：〜たり〜たりしました。たり 前面永远是た形（した、見た）。',
      zh: '周末逛了逛街、看了看电影。',
    },
  ],
  lessonWords: [
    {
      ja: '洗濯する',
      zh: '洗衣服',
      example: '天気がいい日に洗濯します。',
      audio: `${AUDIO}/lesson-01-example.m4a`,
      termAudio: `${AUDIO}/lesson-01-term.m4a`,
      quiz: '汚れた服をきれいに洗うことを「___」と言う。',
    },
    {
      ja: 'えらい',
      zh: '了不起；真勤快',
      example: '弟は毎日自分で部屋を掃除して、えらいです。',
      audio: `${AUDIO}/lesson-02-example.m4a`,
      termAudio: `${AUDIO}/lesson-02-term.m4a`,
      quiz: 'ちゃんと頑張っている人をほめるときに「___ですね」と言う。',
    },
    {
      ja: '実は',
      zh: '其实；说实话',
      example: '実は、明日は来られないんです。',
      audio: `${AUDIO}/lesson-03-example.m4a`,
      termAudio: `${AUDIO}/lesson-03-term.m4a`,
      quiz: '本当のことをこれから言うときに、文の最初に「___」と言う。',
    },
    {
      ja: '一日中',
      zh: '一整天',
      example: '雨で、一日中家にいました。',
      audio: `${AUDIO}/lesson-04-example.m4a`,
      termAudio: `${AUDIO}/lesson-04-term.m4a`,
      quiz: '朝から夜までずっとのことを「___」と言う。',
    },
    {
      ja: 'やっぱり',
      zh: '果然；我就知道',
      example: 'やっぱり、家のご飯が一番おいしいです。',
      audio: `${AUDIO}/lesson-05-example.m4a`,
      termAudio: `${AUDIO}/lesson-05-term.m4a`,
      quiz: '思っていたとおりだったときに「___」と言う。',
    },
  ],
  bonusWords: [
    { ja: '休日', zh: '休息日', example: '休日はたいてい家にいます。', audio: `${AUDIO}/word-01-example.m4a`, termAudio: `${AUDIO}/word-01-term.m4a`, quiz: '学校や仕事がない日を「___」と言う。' },
    { ja: '予定', zh: '安排；计划', example: '今週末は何も予定がありません。', audio: `${AUDIO}/word-02-example.m4a`, termAudio: `${AUDIO}/word-02-term.m4a`, quiz: 'これからすることに決めていることを「___」と言う。' },
    { ja: '趣味', zh: '爱好', example: '私の趣味は写真を撮ることです。', audio: `${AUDIO}/word-03-example.m4a`, termAudio: `${AUDIO}/word-03-term.m4a`, quiz: '好きで、時間があるときにすることを「___」と言う。' },
    { ja: '出かける', zh: '出门', example: '日曜日は朝から出かけました。', audio: `${AUDIO}/word-04-example.m4a`, termAudio: `${AUDIO}/word-04-term.m4a`, quiz: '家から外へ行くことを「___」と言う。' },
    { ja: '散歩する', zh: '散步', example: '夕方、犬と公園を散歩します。', audio: `${AUDIO}/word-05-example.m4a`, termAudio: `${AUDIO}/word-05-term.m4a`, quiz: 'ゆっくり外を歩くことを「___」と言う。' },
    { ja: '料理する', zh: '做饭', example: '週末は自分で料理します。', audio: `${AUDIO}/word-06-example.m4a`, termAudio: `${AUDIO}/word-06-term.m4a`, quiz: 'ご飯を作ることを「___」と言う。' },
    { ja: '片付ける', zh: '收拾', example: '使ったお皿を片付けてください。', audio: `${AUDIO}/word-07-example.m4a`, termAudio: `${AUDIO}/word-07-term.m4a`, quiz: '出した物を元の所に戻すことを「___」と言う。' },
    { ja: 'ゆっくりする', zh: '悠闲地休息', example: '今日は家でゆっくりしたいです。', audio: `${AUDIO}/word-08-example.m4a`, termAudio: `${AUDIO}/word-08-term.m4a`, quiz: '急がないで、のんびり休むことを「___」と言う。' },
    { ja: '運動する', zh: '运动', example: '健康のために毎日運動しています。', audio: `${AUDIO}/word-09-example.m4a`, termAudio: `${AUDIO}/word-09-term.m4a`, quiz: '体を動かしてスポーツなどをすることを「___」と言う。' },
    { ja: '遊ぶ', zh: '玩', example: '子どもたちが公園で遊んでいます。', audio: `${AUDIO}/word-10-example.m4a`, termAudio: `${AUDIO}/word-10-term.m4a`, quiz: '好きなことをして楽しく過ごすことを「___」と言う。' },
    { ja: '昼寝する', zh: '午睡', example: '日曜日の午後に少し昼寝しました。', audio: `${AUDIO}/word-11-example.m4a`, termAudio: `${AUDIO}/word-11-term.m4a`, quiz: '昼に少し寝ることを「___」と言う。' },
    { ja: 'ドラマ', zh: '电视剧', example: '毎晩、韓国のドラマを見ています。', audio: `${AUDIO}/word-12-example.m4a`, termAudio: `${AUDIO}/word-12-term.m4a`, quiz: 'テレビで毎週続けて見る物語を「___」と言う。' },
  ],
  sentence: {
    marker: '(た|だ)り.*(た|だ)りし',
    markerNoSpace: 'ましたり',
    spacingLabel: '写法：たり 前面用た形，没有写成「〜ましたり」',
    displayName: '〜たり〜たりする',
    meaningSide: 'before',
    meaningLabel: '句意完整：たり 前面至少写出两件事',
    starters: ['休みの日は', '旅行では', '雨の日は'],
    placeholder: '例：休みの日は本を読んだり、散歩をしたりします。',
  },
  sentenceTitle: '用 〜たり〜たりする 说说看',
};
